# ==========================================================
# Kong core defaults
# ==========================================================

kong_database: postgres

# ==========================================================
# PostgreSQL connection (used by kong.conf.j2)
# ==========================================================

pg_host: "{{ postgres_vm_ip }}"
pg_port: 5432
pg_user: kong
pg_password: kongpass
pg_database: kong

# ==========================================================
# Kong ports
# ==========================================================

kong_proxy_port: 8000
kong_admin_port: 8001
