# ==========================================================
# Kong core defaults
# ==========================================================

kong_database: postgres

# ==========================================================
# PostgreSQL defaults for Kong
# ==========================================================

pg_user: kong
pg_password: kongpass
pg_database: kong
pg_port: 5432


# ==========================================================
# Kong ports
# ==========================================================

kong_proxy_port: 8000
kong_admin_port: 8001
