---
- name: Prepare dynamic inventory from workflow survey
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Add Postgres host with IP
      add_host:
        name: postgres
        ansible_host: "{{ postgres_vm_ip }}"

    - name: Add Kong host with IP
      add_host:
        name: kong
        ansible_host: "{{ kong_vm_ip }}"
